## Практическое заданий №1

Задание__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

Чтобы перемножить матрицы количество чтолбцов 1-ой матрицы должно равняться кол-ву строк 2-й матрицы. Исходя из этого правила следует:

а) перемножение матриц $A*B$ как и $B*A$ невозможно, так как кол-во столбцов != количеству строк

б) $A*B$ можно перемножить, т.к. число столбцов матрицы $А$ (равное 5) равно числу строк матрицы $В$ (равное 5) получим матрицу:

$2х3$

$B*A$ перемножить нельзя из-за неравенстра столбцов и строк

In [1]:
import numpy as np

In [2]:
A = np.random.randint (0, 10, (2, 5))
B = np.random.randint (0, 10, (5, 3))
A, B

(array([[0, 5, 9, 9, 6],
        [4, 9, 0, 4, 2]]),
 array([[3, 1, 7],
        [8, 6, 8],
        [1, 5, 7],
        [5, 1, 0],
        [0, 9, 6]]))

In [3]:
AB = np.dot(A, B)
AB

array([[ 94, 138, 139],
       [104,  80, 112]])

In [4]:
AB.shape

(2, 3)

в) $АB$ и $ВА$ перемножить можно так как число столбцов и строк равны в обоих случаях, в первом получим:

$8x8$, во втором $3x3$

In [5]:
A = np.random.randint (0, 10, (8, 3))
B = np.random.randint (0, 10, (3, 8))
A,B

(array([[3, 0, 6],
        [2, 9, 9],
        [5, 3, 4],
        [2, 5, 7],
        [2, 2, 3],
        [1, 2, 5],
        [0, 8, 1],
        [0, 0, 6]]),
 array([[3, 6, 8, 7, 6, 7, 7, 2],
        [4, 9, 7, 8, 8, 5, 5, 6],
        [2, 9, 9, 5, 1, 9, 2, 3]]))

In [6]:
AB = np.dot(A, B)
BA = np.dot(B, A)

In [7]:
AB.shape, BA.shape

((8, 8), (3, 3))

г) $AB$ и $BA$ перемножить можно, так как матрицы квадратные $m=n=4$. Получим $AB$ и $BA$ с размерностью $4$

Задание__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$


Решение:

$A*B$ = 
$\begin{pmatrix}
1*4 + (-2)*0 & (-1)*1 + (-2)*5\\ 
3*4 + 0*0 &  3*(-1) + 0*5
\end{pmatrix}$
=$\begin{pmatrix}
4 & -11\\ 
12 &-3
\end{pmatrix}$

$A+B$ = 
$\begin{pmatrix}
1+4 & -2-1\\ 
3+0 &  0+5
\end{pmatrix}$
=$\begin{pmatrix}
5 & -3\\ 
3 & 5
\end{pmatrix}$

In [8]:
A = np.array([[1, -2],
     [3, 0]])
B = np.array([[4, -1], 
     [0, 5]])
AB = np.dot(A,B)
BA = np.dot(B,A)

In [9]:
AB, BA

(array([[  4, -11],
        [ 12,  -3]]),
 array([[ 1, -8],
        [15,  0]]))

In [10]:
A+B

array([[ 5, -3],
       [ 3,  5]])

Задание__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

In [11]:
A = np.array([[1, 7],
     [3, -6]])
B = np.array([[0, 5], 
     [2, -1]])
C = np.array([[2, -4], [1, 1]])

$3A-2B+4C$ = 
$\begin{pmatrix}
3 & 21\\ 
9 & -18
\end{pmatrix}$
-$\begin{pmatrix}
0 & 10\\ 
4 & -2
\end{pmatrix}$
+$\begin{pmatrix}
8 & -16\\ 
4 & 4
\end{pmatrix}$
=$\begin{pmatrix}
3-0+8 & 21-10-16\\ 
9-4+4 &-18+4+4
\end{pmatrix}$
=$\begin{pmatrix}
11 & -5\\ 
9 &-12
\end{pmatrix}$

In [12]:
3*A-2*B+4*C

array([[ 11,  -5],
       [  9, -12]])

Задание__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

Решение:

$A^{T}$ = 
$\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix}$ - транспонирование матрицы А

$A*A^{T}$ = 
$\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$
*
$\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix}$
=
$\begin{pmatrix}
4*4 + 1*1 & 4*5 + 1*(-2) & 4*2 + 1*3\\ 
5*4 + (-2)*1 & 5*5 + (-2)*(-2) & 5*2 + (-2)*3\\
2*4 + 3*1 & 2*5 + 3*(-2) & 2*2 + 3*3
\end{pmatrix}$
=
$\begin{pmatrix}
17 & 18 & 11\\ 
18 & 29 & 4\\
11 & 4 & 13
\end{pmatrix}$


$A^{T}*A$ = 
$\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix}$
*
$\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$
=
$\begin{pmatrix}
4*4 + 5*5 + 2*2 & 4*1 + 5*(-2) + 2*3 \\ 
1*4 + (-2)*5 + 3*2 & 1*1 + (-2)*(-2) + 3*3 \\
\end{pmatrix}$
=
$\begin{pmatrix}
45 & 0\\ 
0 & 14
\end{pmatrix}$


In [13]:
A = np.array([[4, 1], 
              [5, -2], 
              [2, 3]])

In [14]:
A.T # транспонирование матрицы A

array([[ 4,  5,  2],
       [ 1, -2,  3]])

In [15]:
AAt = np.dot(A,A.T)
AtA = np.dot(A.T,A)

In [16]:
AAt, AtA

(array([[17, 18, 11],
        [18, 29,  4],
        [11,  4, 13]]),
 array([[45,  0],
        [ 0, 14]]))

Задание__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [28]:
class Matrix:
 def __init__(self, matrix):
     self.matrix= matrix
 def __str__(self):
     return ','.join(map(str, self.matrix)).replace(']', '\n').replace('[', '').replace(',', '')
 def __add__(self, other):
     if len(self.matrix) == len(other.matrix):
         for row1, row2 in zip(self.matrix, other.matrix):
             if len(row1) != len(row2):
                 return f'Количество столбцов не равно, эти матрицы нельзя сложить'
         result = [[a + b for a, b in zip(row1, row2)] for row1, row2 in zip(self.matrix, other.matrix)]
         return ','.join(map(str, result)).replace(']', '\n').replace('[', '').replace(',', '')
     else:
         return f'Количество строк не равно, эти матрицы нельзя сложить'

 def __mul__(self, other):
     result = []
     try:
         for row in self.matrix:
             row_result = []
             for i in range(len(other.matrix[0])):
                 num = 0
                 for idx, el in enumerate(row):
                     num += (el * other.matrix[idx][i])
                 row_result.append(num)
             result.append(row_result)
         return ','.join(map(str, result)).replace(']', '\n').replace('[', '').replace(',', '')
     except:
         return f'Умножение матриц данной размерности невозможно'


    
a1 = np.random.randint (0, 10, (3, 5))
b1 = np.random.randint (0, 10, (5, 3))
A = Matrix(a1)
B = Matrix(b1)
print(f"Матрица А:\n{A}")
print(f"Матрица B:\n{B}")
print(f"Матрица А+B:\n{A + B}")

c1 = np.random.randint (0, 10, (3, 2))
d1 = np.random.randint (0, 10, (3, 5))

C = Matrix(c1)
D = Matrix(d1)

print(f"Умножение A*B:\n{A * B}")
print(f"Умножение C*D:\n{C * D}")
print(f"Сложение C+D:\n{C + D}")
print(f"Умножение D*C:\n{D * C}")

Матрица А:
6 4 4 9 6
1 7 6 8 0
9 9 6 5 8

Матрица B:
6 0 9
8 4 1
8 9 7
3 0 9
0 1 7

Матрица А+B:
Количество строк не равно, эти матрицы нельзя сложить
Умножение A*B:
127 58 209
134 82 130
189 98 233

Умножение C*D:
31 30 25 36 32
68 60 50 18 76
37 36 30 45 38

Сложение C+D:
Количество столбцов не равно, эти матрицы нельзя сложить
Умножение D*C:
Умножение матриц данной размерности невозможно


## Практическое заданий №2

Задание__1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

а) $ sinx*sinx - cosx*(-cosx)$ = $sin^{2}x$ + $cos^{2}x$ = 1

б)
$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix}$
= $4*(5*9 - 1*0) - 2*(0*9 - 0*1) + 3*(0*0 - 0*5)$ = $4*45$ = $180$

в)
$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}$
= $1*(5*9 - 6*8) - 2*(4*9 - 7*6) + 3*(4*8 - 7*5)$ = $1*(45-78) - 2*(36-42) + 3*(32-35)$ = 

$-3 + 12 - 9$ = $-12+12$ = $0$

In [18]:
a = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
np.linalg.det(a)

180.0

In [19]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
round(np.linalg.det(b), 2)

0.0

Задание__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.
   

а) $det(A^{2})$ = $4*4$ = $16$

б) $det(A^{T})$ = $4$, т.к. определитель транспонированной матрицы равен определителю исходной матрицы

в) $det(2A)$ = $2^{n}$ * $4$ = $2^{n}$ * $2^{2}$ = $2^{n+2}$

Задание__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$
= $-2*(-14*13 - 6*7) - 7*(4*13 - 3*(-6)) + (-3)*(4*7 - (-3)*(-14))$ = $-2*(-224) - 7*(70) + (-3)*(-14)$=
$448-490+42$ = $0$ - определитель матрицы равено НУЛЮ

Значит матрица является вырожденной

In [20]:
a = np.array([[-2, 7, -3], 
              [4, -14, 6],
              [-3, 7, 13]])
np.linalg.det(a)

0.0

Задание__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

Решение:

а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix}$, 3 строка равняется суммой 1-й и 2-й, ее можно отбросить
$\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1
\end{pmatrix}$ и из 2-й строки вычтем 1-ю
$\begin{pmatrix}
1 & 2 & 3\\ 
0 & -1 & -2
\end{pmatrix}$

In [21]:
a = np.array([[1, 2, 3], 
              [1, 1, 1],
              [2, 3, 4]])
np.linalg.matrix_rank(a)

2

 б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}$
передвинем нижню строку наверх
$\begin{pmatrix}
2 & 3 & 5 & 6\\
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3
\end{pmatrix}$
вычтем их последней строки 2-ю строку 2 раза
$\begin{pmatrix}
2 & 3 & 5 & 6\\
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 0 & 1
\end{pmatrix}$

In [23]:
b.T

array([[0, 0, 0, 2],
       [0, 0, 0, 3],
       [2, 2, 4, 5],
       [1, 2, 3, 6]])

In [22]:
b = np.array([[0, 0, 2, 1], 
              [0, 0, 2, 2], 
              [0, 0, 4, 3], 
              [2, 3, 5, 6]])
np.linalg.matrix_rank(b)

3