In [1]:
import numpy as np

###  Часть 1

Задание__1.__ Решить систему уравнений методом Гаусса:

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$$

Решение: 
    
Можно привести к виду:

$$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2\\ 
2 & 1 & -1 & 1 \\ 
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}.$$

Вычтем их второй строки первую, и из третье - первую:

$$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2\\ 
1 & 0 & 0 & 3 \\ 
0 & 0 & -2 & 3
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}.$$


$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
x_{1}+3x_{4}=-2, \\
-2x_{3}+3x_{4}=4.
\end{cases}$$

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
x_{1}=-3x_{4}-2, \\
3x_{4}-4=2x_{3}
\end{cases}$$

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
x_{1}=-3x_{4}-2, \\
\frac{3}{2}x_{4}-2=x_{3}
\end{cases}$$

$$\begin{cases}
-3x_{4}-2+x_{2}-\frac{3}{2}x_{4}+2-2x_{4}=0, \\
x_{1}=-3x_{4}-2, \\
x_{3} = \frac{3}{2}x_{4}-2
\end{cases}$$

$$\begin{cases}
-6x_{4}-4+2x_{2}-3x_{4}+4-4x_{4}=0, \\
x_{1}=-3x_{4}-2, \\
x_{3} = \frac{3}{2}x_{4}-2
\end{cases}$$

$$\begin{cases}
-13x_{4}+2x_{2}=0, \\
x_{1}=-3x_{4}-2, \\
x_{3} = \frac{3}{2}x_{4}-2
\end{cases}$$

$$\begin{cases}
x_{2}=\frac{13}{2}x_{4} = 6\frac{1}{2}x_{4}, \\
x_{1}=-3x_{4}-2, \\
x_{3} = \frac{3}{2}x_{4}-2
\end{cases}$$

__2.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$
    
   в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$


Решение а):
    
а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$

$$\begin{pmatrix}
\left.\begin{matrix}
3 & -1 & 1\\ 
2 & -5 & -3 \\ 
1 & 1 & -1 
\end{matrix}\right|
\begin{matrix}
4\\ 
-17\\
0
\end{matrix}
\end{pmatrix}$$

Прибавил к третьему первое:

$$\begin{pmatrix}
\left.\begin{matrix}
3 & -1 & 1\\ 
2 & -5 & -3 \\ 
4 & 0 & 0 
\end{matrix}\right|
\begin{matrix}
4\\ 
-17\\
4
\end{matrix}
\end{pmatrix}$$

из второго вычтем первоем умноженное на 5:

$$\begin{pmatrix}
\left.\begin{matrix}
3 & -1 & 1\\ 
-13 & 0 & -8 \\ 
4 & 0 & 0 
\end{matrix}\right|
\begin{matrix}
4\\ 
-37\\
4
\end{matrix}
\end{pmatrix}$$

$$\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
-13x_{1}-8x_{3}=-37, \\
x_{1}=1.
\end{cases}$$

Подставляем $x_{1}=1$ во второе уравнение и 1-ое

$\begin{cases}
3-x_{2}+x_{3}=4 \\
-13-8x_{3}=-37 \\
x_{1}=1
\end{cases}$,
$\begin{cases}
3-x_{2}+x_{3}=4 \\
8x_{3}=-13+37=24 \\
x_{1}=1
\end{cases}$,
$\begin{cases}
3-x_{2}+x_{3}=4\\
x_{3}=3 \\
x_{1}=1
\end{cases}$

Подставляем $x_{3}=3$ в первое:

$\begin{cases}
3-x_{2}+3=4 \\
x_{3}=3 \\
x_{1}=1
\end{cases}$,
$\begin{cases}
x_{2}=2 \\
x_{3}=3 \\
x_{1}=1
\end{cases}$,

система линейных уравнений имеет 3 решения

Необходимым и достаточным условием совместности системы является равенство между собой рангов матрицы коэффициентов $A$ и расширенной матрицы $\tilde A$

$$rank A=rank \tilde A.$$

$$A = \begin{pmatrix}
\begin{matrix}
3 & -1 & 1\\ 
2 & -5 & -3 \\ 
1 & 1 & -1 
\end{matrix}
\end{pmatrix}$$

$$\tilde A =
\begin{pmatrix}
\left.\begin{matrix}
3 & -1 & 1\\ 
2 & -5 & -3 \\ 
1 & 1 & -1 
\end{matrix}\right|
\begin{matrix}
4\\ 
-17\\
0
\end{matrix}
\end{pmatrix}$$

In [63]:
A = np.array([[3, -1, 1], 
              [2, -5, -3], 
              [1, 1, -1]])
b = np.array([4, -17, 0])[:, np.newaxis]
A_extended = np.hstack((A, b))
rank_A = np.linalg.matrix_rank(A)
rank_A_extended = np.linalg.matrix_rank(A_extended)
print(f'A_extended: \n{A_extended}')
print(f'rank A = {rank_A}')
print(f'rank A_extended = {rank_A_extended}')
if rank_A == rank_A_extended:
    print(f'Система линейныйх уравнений - совместна')
else:
    print(f'Система линейныйх уравнений - несовместна')
print(f'Решение: n\ {np.linalg.solve(A, b)}')

A_extended: 
[[  3  -1   1   4]
 [  2  -5  -3 -17]
 [  1   1  -1   0]]
rank A = 3
rank A_extended = 3
Система линейныйх уравнений - совместна
Решение: n\ [[1.]
 [2.]
 [3.]]


Решение б):
    
$\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$

$$ A=\begin{pmatrix}
\begin{matrix}
2 & -4 & 6\\ 
1 & -2 & 3 \\ 
3 & -6 & 9 
\end{matrix}
\end{pmatrix}$$

Для $A$ из третье строки вычтем 2-ю и 1-ю, а из 2-й умноженной на 2 вычтем первую:

$ A = \begin{pmatrix}
\begin{matrix}
2 & -4 & 6\\ 
0 & 0 & 0 \\ 
0 & 0 & 0 
\end{matrix}
\end{pmatrix}$, таким образом $rankA = 1$


$$ \tilde A=\begin{pmatrix}
\left.\begin{matrix}
2 & -4 & 6\\ 
1 & -2 & 3 \\ 
3 & -6 & 9 
\end{matrix}\right|
\begin{matrix}
1\\ 
-2\\
5
\end{matrix}
\end{pmatrix}$$

Аналогично для $\tilde A$:

$\begin{pmatrix}
\left.\begin{matrix}
2 & -4 & 6\\ 
1 & -2 & 3  \\ 
0 & 0 & 0 
\end{matrix}\right|
\begin{matrix}
1\\ 
-2\\
6
\end{matrix}
\end{pmatrix}$,
$\begin{pmatrix}
\left.\begin{matrix}
2 & -4 & 6\\ 
2 & -4 & 6  \\ 
0 & 0 & 0 
\end{matrix}\right|
\begin{matrix}
1\\ 
-4\\
6
\end{matrix}
\end{pmatrix}$,
$\begin{pmatrix}
\left.\begin{matrix}
2 & -4 & 6\\ 
0 & 0 & 0  \\ 
0 & 0 & 0 
\end{matrix}\right|
\begin{matrix}
1\\ 
-5\\
6
\end{matrix}
\end{pmatrix}$, прибавляем к 3-й стоке 2-ю:
$\begin{pmatrix}
\left.\begin{matrix}
2 & -4 & 6\\ 
0 & 0 & 0  \\ 
0 & 0 & 0 
\end{matrix}\right|
\begin{matrix}
1\\ 
-5\\
1
\end{matrix}
\end{pmatrix}$

Умножаем третью строку на 5:

$\begin{pmatrix}
\left.\begin{matrix}
2 & -4 & 6\\ 
0 & 0 & 0  \\ 
0 & 0 & 0 
\end{matrix}\right|
\begin{matrix}
1\\ 
-5\\
5
\end{matrix}
\end{pmatrix}$

и прибавляем 2-ю строку к третьей:

$\begin{pmatrix}
\left.\begin{matrix}
2 & -4 & 6\\ 
0 & 0 & 0  \\ 
0 & 0 & 0 
\end{matrix}\right|
\begin{matrix}
1\\ 
-5\\
0
\end{matrix}
\end{pmatrix}$, таким образом $rank \tilde A = 2$

$rankA < rank \tilde A$ значит система линейных уравнений НЕ совместна

Также ранг меньше количества неизвестных $ x_{1},x_{2}, x_{3}$ которых $3$, и число больше ранга, значит решения нет.

In [58]:
A = np.array([[2, -4, 6], 
              [1, -2, 3], 
              [3, -6, 9]])
b = np.array([1, -2, 5])[:, np.newaxis]
A_extended = np.hstack((A, b))
rank_A = np.linalg.matrix_rank(A)
rank_A_extended = np.linalg.matrix_rank(A_extended)
print(f'A_extended: \n{A_extended}')
print(f'rank A = {rank_A}')
print(f'rank A_extended = {rank_A_extended}')
if rank_A == rank_A_extended:
    print(f'Система линейныйх уравнений - совместна')
else:
    print(f'Система линейныйх уравнений - несовместна')

A_extended: 
[[ 2 -4  6  1]
 [ 1 -2  3 -2]
 [ 3 -6  9  5]]
rank A = 1
rank A_extended = 2
Система линейныйх уравнений - несовместна


Решение в)

$\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$

$$ A=\begin{pmatrix}
\begin{matrix}
2 & 2 & 5\\ 
3 & 1 & -8
\end{matrix}
\end{pmatrix}$$

$$ \tilde A=\begin{pmatrix}
\left.\begin{matrix}
2 & 2 & 5\\ 
3 & 1 & -8
\end{matrix}\right|
\begin{matrix}
4\\ 
-2
\end{matrix}
\end{pmatrix}$$

какие бы манипуляции не делали $rankA$ = $rank\tilde A = 2$
<br>если $rankA=rank \tilde A<n$, где $n$ -число неизвестных, то система имеет бесконечное количество решений. 
<br>В нашем случае число неизвестных $ x_{1},x_{2}, x_{3}$ равно $3$, значит решений бесконечное кол-во.

In [73]:
A = np.array([[1, 2, 5], 
              [3, 1, -8]])
b = np.array([4, -2])[:, np.newaxis]
A_extended = np.hstack((A, b))
rank_A = np.linalg.matrix_rank(A)
rank_A_extended = np.linalg.matrix_rank(A_extended)
print(f'A_extended: \n{A_extended}')
print(f'rank A = {rank_A}')
print(f'rank A_extended = {rank_A_extended}')
if rank_A == rank_A_extended:
    print(f'Система линейныйх уравнений - совместна')
else:
    print(f'Система линейныйх уравнений - несовместна')

A_extended: 
[[ 1  2  5  4]
 [ 3  1 -8 -2]]
rank A = 2
rank A_extended = 2
Система линейныйх уравнений - совместна


Задание__3.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$$

Решение:

$$A=\begin{pmatrix}
\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\
\end{pmatrix}.$$

Видим, что ранг $A$ и $\tilde{A}$ равен $4$. Но также количество неизвестных $ x_{1},x_{2}, x_{3}, x_{4}$ равно $4$.

если $rankA=rank \tilde A=n$, где $n$ — число неизвестных, то система определена, т. е. имеет единственное решение<br>

$\begin{cases}
x_{1}+3x_{2}-2x_{3}+4x_{4}=3 \\
5x_{2}+x_{4}=2 \\
3x_{3}=4\\
x_{4}=\frac{1}{2}
\end{cases}$,
$\begin{cases}
x_{1}+3x_{2}-2x_{3}+4x_{4}=3 \\
5x_{2}+x_{4}=2 \\
x_{3}=1\frac{1}{3}\\
x_{4}=\frac{1}{2}
\end{cases}$,
$\begin{cases}
x_{1}+3x_{2}-2x_{3}+4x_{4}=3 \\
5x_{2}=2-\frac{1}{2} = \frac{3}{2} \\
x_{3}=1\frac{1}{3}\\
x_{4}=\frac{1}{2}
\end{cases}$,
$\begin{cases}
x_{1}+3x_{2}-2x_{3}+4x_{4}=3 \\
x_{2}= \frac{3}{10} \\
x_{3}=1\frac{1}{3}\\
x_{4}=\frac{1}{2}
\end{cases}$,

$\begin{cases}
x_{1}+\frac{9}{10}-\frac{8}{3}+2=3 \\
x_{2}= \frac{1}{2} \\
x_{3}=1\frac{1}{3}\\
x_{4}=\frac{1}{2}
\end{cases}$,
$\begin{cases}
x_{1}=1+\frac{8}{3}-\frac{9}{10}=\frac{30+80-27}{30}=\frac{83}{30}= 2\frac{23}{30}\\
x_{2}= \frac{1}{2} \\
x_{3}=1\frac{1}{3}\\
x_{4}=\frac{1}{2}
\end{cases}$.


In [72]:
A = np.array([[1, 3, -2, 4], 
              [0, 5, 0, 1],
             [0, 0, 3, 0],
             [0, 0, 0, 2]])
b = np.array([3, 2, 4, 1])[:, np.newaxis]
A_extended = np.hstack((A, b))
rank_A = np.linalg.matrix_rank(A)
rank_A_extended = np.linalg.matrix_rank(A_extended)
print(f'A: \n{A}')
print(f'rank A = {rank_A}')
print(f'rank A_extended = {rank_A_extended}')
if rank_A == rank_A_extended:
    print(f'Система линейныйх уравнений - совместна')
else:
    print(f'Система линейныйх уравнений - несовместна')

A: 
[[ 1  3 -2  4]
 [ 0  5  0  1]
 [ 0  0  3  0]
 [ 0  0  0  2]]
rank A = 4
rank A_extended = 4
Система линейныйх уравнений - совместна


In [68]:
print(f'Решение: n\ {np.linalg.solve(A, b)}')

Решение: n\ [[2.76666667]
 [0.3       ]
 [1.33333333]
 [0.5       ]]


Задание__4.__ Дана система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$$

Найти соотношение между параметрами $a$, $b$ и $c$, при которых система является несовместной.

Решение:

$$A=\begin{pmatrix}
\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}
\end{pmatrix}.$$
    
Вычтем и 3-й строки вторую умноженную на 2 и прибавим первую:

$A=\begin{pmatrix}
\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
-1 & -2 & -3
\end{matrix}
\end{pmatrix}$,
$\begin{pmatrix}
\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
0 & 0 & 0
\end{matrix}
\end{pmatrix}$, получим $rankA=2$

Аналогично для $\tilde A$:

Вычтем из 3-ей строки вторую умноженную на 2:
$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
-1 & -2 & -3
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c-2b
\end{matrix}
\end{pmatrix}$$

Далее прибавляем к 3-ей - 1ую строку:

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
0 & 0 & 0
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c-2b+a
\end{matrix}
\end{pmatrix}$$

чтобы система была несовместна $rankA \neq rank \tilde A$

Значит нужно чтобы $c-2b+a \neq0$, тогда $rank \tilde A$ будет равен $3$


In [79]:
A = np.array([[1, 2, 3], 
              [4, 5, 6,],
             [7, 8, 9]])
rank_A = np.linalg.matrix_rank(A)
print(f'A: \n{A}')
print(f'rank A = {rank_A}')

A: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
rank A = 2


### Часть 2

Задача__1.__ Решить систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$


Решение а)

Для системы с $n$ уравнениями и $n$ неизвестными, если система уравнений невырождена (то есть $detA\neq 0$), то система определена, то есть имеет единственное решение, и это решение может быть найдено по формулам Крамера:

$$x_{i}=\frac{detA_{i}}{detA},$$

где $A_{i}$ — это матрица, получаемая заменой $i$-го столбца на вектор-столбец свободных членов $b$.

$detA=\begin{vmatrix}
1 & -2\\ 
3 & -4
\end{vmatrix}=1 \cdot (-4)-3\cdot (-2) =-4+6 = 2\neq 0,$ система совместна

$detA_{1}=\begin{vmatrix}
1 & -2\\ 
7 & -4
\end{vmatrix}=1 \cdot (-4)-7\cdot (-2) =-4+14 = 10$

$detA_{2}=\begin{vmatrix}
1 & 1\\ 
3 & 7
\end{vmatrix}=1 \cdot 7-3\cdot 1 =7-3 = 4$

$x_{1} = \frac{detA_{1}}{detA} = \frac{10}{2}=5$

$x_{2} = \frac{detA_{2}}{detA} = \frac{4}{2}=2$

б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

$detA=\begin{vmatrix}
2 & -1 & 5\\ 
1 & 1 & -3 \\
2 & 4 & 1
\end{vmatrix}= 
2\begin{vmatrix}
1 & -3\\ 
4 & 1
\end{vmatrix}+
\begin{vmatrix}
1 & -3\\ 
2 & 1
\end{vmatrix}+
5\begin{vmatrix}
1 & 1\\ 
2 & 4
\end{vmatrix}=2(1+12)+(1+6)+5(4-2)=26+7+10=43\neq 0
$


$detA_{1}=\begin{vmatrix}
10 & -1 & 5\\ 
-2 & 1 & -3 \\
1 & 4 & 1
\end{vmatrix}= 
10\begin{vmatrix}
1 & -3\\ 
4 & 1
\end{vmatrix}+
\begin{vmatrix}
-2 & -3\\ 
1 & 1
\end{vmatrix}+
5\begin{vmatrix}
-2 & 1\\ 
1 & 4
\end{vmatrix}=10(1+12)+(-2+3)+5(-8-1)=130+1-45=86
$

$x_{1} = \frac{detA_{1}}{detA} = \frac{86}{43}=2$

$detA_{2}=\begin{vmatrix}
2 & 10 & 5\\ 
1 & -2 & -3 \\
2 & 1 & 1
\end{vmatrix}= 
2\begin{vmatrix}
-2 & -3\\ 
1 & 1
\end{vmatrix}-
10\begin{vmatrix}
1 & -3\\ 
2 & 1
\end{vmatrix}+
5\begin{vmatrix}
1 & -2\\ 
2 & 1
\end{vmatrix}=2(-2+3)-10(1+6)+5(1+4)=2-70+24=-43
$

$x_{2} = \frac{detA_{2}}{detA} = \frac{-43}{43}=-1$

$detA_{3}=\begin{vmatrix}
2 & -1 & 10\\ 
1 & 1 & -2 \\
2 & 4 & 1
\end{vmatrix}= 
2\begin{vmatrix}
1 & -2\\ 
4 & 1
\end{vmatrix}+
\begin{vmatrix}
1 & -2\\ 
2 & 1
\end{vmatrix}+
10\begin{vmatrix}
1 & 1\\ 
2 & 4
\end{vmatrix}=2(1+8)+(1+4)+10(4-2)=18+5+20=43
$

$x_{3} = \frac{detA_{3}}{detA} = \frac{43}{43}=1$

In [116]:
def kramer(A, b):
    det_A = np.linalg.det(A)
    print(f'detA равен = {det_A}')
    result = []
    if np.abs(det_A) > 0:
        for i in range(A.shape[0]):
            A_i = np.hstack((A[:, :i], b, A[:, i+1:]))
            result.append(np.linalg.det(A_i) / det_A)
        return np.round(result, 2)
    else:
        return 'det A равен нулю'

In [117]:
A = np.array([[1, -2], 
              [3, -4]])
B = np.array([[1, 7]]).T
print(f'Решение а): {kramer(A, B)}')

detA равен = 2.0000000000000004
Решение а): [5. 2.]


In [118]:
A = np.array([[2, -1, 5], 
              [1, 1, -3], 
              [2, 4, 1]])
b = np.array([[10, -2, 1]]).T
print(f'Решение б): {kramer(A, b)}')

detA равен = 42.99999999999998
Решение б): [ 2. -1.  1.]


Задание__2*.__ Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   а)$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$
    
   б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$

решение:
    
$$A=LU,$$

где 

$$U=\begin{pmatrix}
a_{11} & a_{12} & a_{13} & a_{14}\\ 
0 & a_{22}^{(1)} & a_{23}^{(1)} & a_{24}^{(1)}\\ 
0 & 0 & 0 & a_{34}^{(2)}\\ 
0 & 0 & 0 & a_{44}^{(3)}\\ 
\end{pmatrix}.$$

$$L=\begin{pmatrix}
1 & 0 & 0 & 0\\ 
m_{21} & 1 & 0 & 0\\ 
m_{31} & m_{32} & 1 & 0\\ 
m_{41} & m_{42} & m_{43} & 1\\ 
\end{pmatrix}.$$

а)$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$

$$L=
\begin{pmatrix}
1 & 0 & 0 \\ 
l_{21} & 1 & 0 \\ 
l_{31} & l_{32} & 1
\end{pmatrix}$$


Умножим первую строку на 2 и вычтем из второй:
$\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
3 & 26 & 30
\end{pmatrix}$ и запишем $l_{21}=2$:

$L-\begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
l_{31} & l_{32} & 1
\end{pmatrix}$, 

далее умножаем первую строку на 3 и вычитаем из третьей:
$\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 20 & 18
\end{pmatrix}$, запишем $l_{31}=3$:

$L-\begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & l_{32} & 1
\end{pmatrix}$, 

Далее умножим вторую строку на 4 и вычтем из третьей:
$\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 0 & 2
\end{pmatrix}$ и запишем $l_{32}=4$:

Получили $L=\begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & 4 & 1
\end{pmatrix}$, 

$A=LU$

$LU=\begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & 4 & 1
\end{pmatrix}\cdot
\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 0 & 2
\end{pmatrix}$

$LU=\begin{pmatrix}
1+0+0 & 2+0+0 & 4+0+0 \\ 
2+0+0 & 4+5+0 & 8+4+0  \\ 
3+0+0 & 6+20+0 & 12+16+2
\end{pmatrix}=
\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 20
\end{pmatrix}$,

$A=LU$

In [156]:
def LU(A):
    assert A.shape[0] == A.shape[1] and A[0][0] !=0 and np.abs(np.linalg.det(A)) > 0.000001
    L = np.zeros_like(A)
    U = np.zeros_like(A)    
    U[0] = A[0]
    L[:, 0] = A[:, 0] / U[0, 0]
    for i in range(A.shape[1]):
        for j in range(i, A.shape[1]):
            U[0, i] = A[0, i]
            L[i, 0] = A[i, 0] / U[0, 0]
            u_sum, l_sum = 0, 0
            for k in range(i):
                u_sum += L[i, k] * U[k, j]
                l_sum += L[j, k] * U[k, i]
            U[i, j] = A[i, j] - u_sum
            L[j, i] = (A[j, i] - l_sum) / U[i, i]
    return U, L

In [151]:
A = np.array([[1, 2, 4], 
              [2, 9, 12], 
              [3, 26, 30]])
U, L = LU(A)
print(f'A: \n{A}')
print(f'U: \n{U}')
print(f'L: \n{L}')
print(f'Проверка LU = \n{L.dot(U)}')
if np.array_equal (A,L.dot(U)):
    print('А = LU, значит решение верно')
else:
    print('Error')

A: 
[[ 1  2  4]
 [ 2  9 12]
 [ 3 26 30]]
U: 
[[1 2 4]
 [0 5 4]
 [0 0 2]]
L: 
[[1 0 0]
 [2 1 0]
 [3 4 1]]
Проверка LU = 
[[ 1  2  4]
 [ 2  9 12]
 [ 3 26 30]]
А = LU, значит решение верно


Решение: 

б) $\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$

$$L=
\begin{pmatrix}
1 & 0 & 0 & 0\\ 
l_{21} & 1 & 0 & 0 \\ 
l_{31} & l_{32} & 1 & 0\\
l_{41} & l_{42} & l_{43} & 1
\end{pmatrix}$$

Умножаем первую строку на 2 и вычитаем из второй:
$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$ и запишем $l_{21}=2$:

$L=
\begin{pmatrix}
1 & 0 & 0 & 0\\ 
2 & 1 & 0 & 0 \\ 
l_{31} & l_{32} & 1 & 0\\
l_{41} & l_{42} & l_{43} & 1
\end{pmatrix}$

Умножаем первую строку на 3 и вычитаем из третьей:
$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 15 & 23 & 6\\
4 & 22 & 53 & 33
\end{pmatrix}$ и запишем $l_{31}=3$:

$L=
\begin{pmatrix}
1 & 0 & 0 & 0\\ 
2 & 1 & 0 & 0 \\ 
3 & l_{32} & 1 & 0\\
l_{41} & l_{42} & l_{43} & 1
\end{pmatrix}$

Умножаем первую строку на 4 и вычитаем из 4-ой строки:
$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 15 & 23 & 6\\
0 & 18 & 45 & 17
\end{pmatrix}$ и запишем $l_{31}=4$:

$L=
\begin{pmatrix}
1 & 0 & 0 & 0\\ 
2 & 1 & 0 & 0 \\ 
3 & l_{32} & 1 & 0\\
4 & l_{42} & l_{43} & 1
\end{pmatrix}$

Умножаем вторую строку на 5 и вычитаем из 3-ей строки:
$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\
0 & 18 & 45 & 17
\end{pmatrix}$ и запишем $l_{32}=5$:

$L=
\begin{pmatrix}
1 & 0 & 0 & 0\\ 
2 & 1 & 0 & 0 \\ 
3 & 5 & 1 & 0\\
4 & l_{42} & l_{43} & 1
\end{pmatrix}$

Умножаем вторую строку на 6 и вычитаем из 4-ей строки:
$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\
0 & 0 & 21 & 11
\end{pmatrix}$ и запишем $l_{42}=6$:

$L=
\begin{pmatrix}
1 & 0 & 0 & 0\\ 
2 & 1 & 0 & 0 \\ 
3 & 5 & 1 & 0\\
4 & 6 & l_{43} & 1
\end{pmatrix}$

Умножаем третью строку на 7 и вычитаем из 4-ей строки:
$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\
0 & 0 & 0 & 4
\end{pmatrix}$ и запишем $l_{42}=7$:

Получили $L=
\begin{pmatrix}
1 & 0 & 0 & 0\\ 
2 & 1 & 0 & 0 \\ 
3 & 5 & 1 & 0\\
4 & 6 & 7 & 1
\end{pmatrix}$

$LU=\begin{pmatrix}
1 & 0 & 0 & 0\\ 
2 & 1 & 0 & 0 \\ 
3 & 5 & 1 & 0\\
4 & 6 & 7 & 1
\end{pmatrix}\cdot
\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\
0 & 0 & 0 & 4
\end{pmatrix}$

$LU=\begin{pmatrix}
1+0+0+0 & 1+0+0+0 & 2+0+0+0 & 4+0+0+0\\ 
2+0+0+0 & 2+3+0+0 & 4+4+0+0 & 8+1+0+0\\ 
3+0+0+0 & 3+15+0+0 & 6+20+3+0 & 12+5+1+0\\
4+0+0+0 & 4+18+0+0 & 8+24+21+0 & 16+6+7+4
\end{pmatrix}=
\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9 \\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$, что верно!

In [153]:
A = np.array([[1, 1, 2, 4], 
              [2, 5, 8, 9], 
              [3, 18, 29, 18], 
              [4, 22, 53,33]])
U, L = LU(A)
print(f'A: \n{A}')
print(f'U: \n{U}')
print(f'L: \n{L}')
print(f'Проверка LU = \n{L.dot(U)}')
if np.array_equal (A,L.dot(U)):
    print('А = LU, значит решение верно')
else:
    print('Error')

A: 
[[ 1  1  2  4]
 [ 2  5  8  9]
 [ 3 18 29 18]
 [ 4 22 53 33]]
U: 
[[1 1 2 4]
 [0 3 4 1]
 [0 0 3 1]
 [0 0 0 4]]
L: 
[[1 0 0 0]
 [2 1 0 0]
 [3 5 1 0]
 [4 6 7 1]]
Проверка LU = 
[[ 1  1  2  4]
 [ 2  5  8  9]
 [ 3 18 29 18]
 [ 4 22 53 33]]
А = LU, значит решение верно


Задание__3*.__ Решить систему линейных уравнений методом $LU$-разложения

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$


Решение:
    
Матрица $A=
\begin{pmatrix}
2 & 1 & 3 \\ 
11 & 7 & 5 \\ 
9 & 8 & 4
\end{pmatrix}$


$L=
\begin{pmatrix}
1 & 0 & 0 \\ 
l_{21} & 1 & 0 \\ 
l_{31} & l_{32} & 1
\end{pmatrix}$

Умножим первую строку на 5 и вычтем из второй:
$\begin{pmatrix}
2 & 1 & 3 \\ 
1 & 2 & -10 \\ 
9 & 8 & 4
\end{pmatrix}$ и запишем $l_{21}=5$:

$L-\begin{pmatrix}
1 & 0 & 0 \\ 
5 & 1 & 0 \\ 
l_{31} & l_{32} & 1
\end{pmatrix}$, 

Умножим первую строку на 4 и вычтем из третьей:
$\begin{pmatrix}
2 & 1 & 3 \\ 
1 & 2 & -10 \\ 
1 & 4 & -8
\end{pmatrix}$ и запишем $l_{31}=4$:

$L-\begin{pmatrix}
1 & 0 & 0 \\ 
5 & 1 & 0 \\ 
4 & l_{32} & 1
\end{pmatrix}$, 

Умножим вторую строку на 2 и вычтем из третьей:
$\begin{pmatrix}
2 & 1 & 3 \\ 
1 & 2 & -10 \\ 
-1 & 0 & 12
\end{pmatrix}$ и запишем $l_{32}=2$:

$L-\begin{pmatrix}
1 & 0 & 0 \\ 
5 & 1 & 0 \\ 
4 & 2 & 1
\end{pmatrix}$, 

Решим теперь систему 

$Ly=b:$

$\begin{cases}
y_{1}=1 \\
5y_{1}+y_{2}=-6 \\
4y_{1}+2y_{2}+y_{3}=-5
\end{cases},
\begin{cases}
y_{1}=1\\
y_{2}=-11\\
4-22+y_{3}=-5
\end{cases},
\begin{cases}
y_{1}=1\\
y_{2}=-11\\
y_{3}=-5+22-4=13
\end{cases}$

$Ux=y:$

$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
x_{1}+2x_{2}-10x_{3}=-11\\
-x_{1}+12x_{3}=13
\end{cases}$

$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
x_{1}+2x_{2}-10x_{3}=-11\\
x_{1}=12x_{3}-13
\end{cases},
\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
12x_{3}-13+2x_{2}-10x_{3}=-11\\
x_{1}=12x_{3}-13
\end{cases},
\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
2x_{3}+2x_{2}=2\\
x_{1}=12x_{3}-13
\end{cases},
\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
x_{3}+x_{2}=1\\
x_{1}=12x_{3}-13
\end{cases},
\begin{cases}
24x_{3}-26+1-x_{3}+3x_{3}=1 \\
x_{3}+x_{2}=1\\
x_{1}=12x_{3}-13
\end{cases}$

$\begin{cases}
26x_{3}-26+1=1 \\
x_{3}+x_{2}=1\\
x_{1}=12x_{3}-13
\end{cases},
\begin{cases}
x_{3}=1 \\
x_{3}+x_{2}=1\\
x_{1}=12x_{3}-13
\end{cases},
\begin{cases}
x_{3}=1 \\
x_{2}=0\\
x_{1}=-1
\end{cases}$

Проверка через Гаусса:
    
Матрица $A=
\begin{pmatrix}
2 & 1 & 3 \\ 
11 & 7 & 5 \\ 
9 & 8 & 4
\end{pmatrix}$


$L=
\begin{pmatrix}
1 & 0 & 0 \\ 
l_{21} & 1 & 0 \\ 
l_{31} & l_{32} & 1
\end{pmatrix}$

Умножим первую строку на 5.5 и вычтем из второй:
$\begin{pmatrix}
2 & 1 & 3 \\ 
0 & 1.5 & -11.5 \\ 
9 & 8 & 4
\end{pmatrix}$ и запишем $l_{21}=5.5$:

$L-\begin{pmatrix}
1 & 0 & 0 \\ 
5.5 & 1 & 0 \\ 
l_{31} & l_{32} & 1
\end{pmatrix}$, 

Умножим первую строку на 4.5 и вычтем из третьей:
$\begin{pmatrix}
2 & 1 & 3 \\ 
0 & 1.5 & -11.5 \\ 
0 & 3.5 & -9.5
\end{pmatrix}$ и запишем $l_{31}=4.5$:

$L-\begin{pmatrix}
1 & 0 & 0 \\ 
5.5 & 1 & 0 \\ 
4.5 & l_{32} & 1
\end{pmatrix}$, 

Умножим вторую строку на 2.33 и вычтем из третьей:
$\begin{pmatrix}
2 & 1 & 3 \\ 
0 & 1.5 & -11.5 \\ 
0 & 0 & \frac{104}{6}
\end{pmatrix}$ и запишем $l_{32}=2.3333$:

$L-\begin{pmatrix}
1 & 0 & 0 \\ 
5.5 & 1 & 0 \\ 
4.5 & 2\frac{1}{3} & 1
\end{pmatrix}$, 

Решим теперь систему 

$Ly=b:$

$\begin{cases}
y_{1}=1 \\
5.5y_{1}+y_{2}=-6 \\
4.5y_{1}+2\frac{1}{3}y_{2}+y_{3}=-5
\end{cases},
\begin{cases}
y_{1}=1\\
y_{2}=-11.5\\
4.5-2\frac{1}{3}\cdot \frac{23}{2}+y_{3}=-5
\end{cases},
\begin{cases}
y_{1}=1\\
y_{2}=-11.5\\
4.5-\frac{7}{3}\cdot \frac{23}{2}+y_{3}=-5
\end{cases},
\begin{cases}
y_{1}=1\\
y_{2}=-11.5\\
4.5-\frac{161}{6}+y_{3}=-5
\end{cases},
\begin{cases}
y_{1}=1\\
y_{2}=-11.5\\
y_{3}=-5-4.5+\frac{161}{6}
\end{cases},
\begin{cases}
y_{1}=1\\
y_{2}=-11.5\\
y_{3}=-\frac{19}{2}+\frac{161}{6}=\frac{-57+161}{6}=\frac{104}{6}=\frac{52}{3}
\end{cases}$

$Ux=y:$

$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
1.5x_{2}-11.5x_{3}=-11.5\\
\frac{52}{3}x_{3}=\frac{52}{3}
\end{cases}$

$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
1.5x_{2}-11.5x_{3}=-11.5\\
x_{3}=1
\end{cases}$

$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
x_{2}=0\\
x_{3}=1
\end{cases}$

$\begin{cases}
x_{1}=-1 \\
x_{2}=0\\
x_{3}=1
\end{cases}$

In [158]:
A = np.array([[2, 1, 3], 
              [11, 7, 5], 
              [9, 8, 4]])
U, L = LU(A)
print(f'A: \n{A}')
print(f'U: \n{U}')
print(f'L: \n{L}')
print(f'Проверка LU = \n{L.dot(U)}')

A: 
[[ 2  1  3]
 [11  7  5]
 [ 9  8  4]]
U: 
[[  2   1   3]
 [  0   2 -10]
 [  0   0  12]]
L: 
[[1 0 0]
 [5 1 0]
 [4 2 1]]
Проверка LU = 
[[ 2  1  3]
 [10  7  5]
 [ 8  8  4]]


Задание__4*.__ Решить систему линейных уравнений методом Холецкого

$$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$$

$$U=\begin{pmatrix}
a_{11} & a_{12} & a_{13} \\ 
a_{21}^{(1)} & a_{22}^{(1)} & a_{23}^{(1)} \\ 
a_{31}^{(2)} & a_{32}^{(2)} & a_{33}^{(2)} 
\end{pmatrix}.$$

$$U=\begin{pmatrix}
81 & -45 & 45 \\ 
-45 & 50 & -15 \\ 
45 & -15 & 38 
\end{pmatrix}.$$

Решение:

Произведем разложение на $LL^{T}$:

$$l_{11}=\sqrt{a_{11}}=\sqrt{81}=9,$$
$$l_{21}=\frac{a_{21}}{l_{11}}=-\frac{45}{9}=-5,$$
$$l_{31}=\frac{a_{31}}{l_{11}}=\frac{45}{9}=5,$$

$$l_{22}=\sqrt{a_{22}-l_{21}^{2}}=\sqrt{50 - 25}=\sqrt{25}=5,$$
$$l_{32}=\frac{1}{l_{22}}\left ( a_{32}-l_{21}l_{31} \right)=\frac{1}{5}\left ( -15 - (-5)\cdot 5 \right)=\frac{1}{5}\left ( -15 +25 \right)=2,$$

$$l_{33}=\sqrt{a_{33}-l_{31}^{2}-l_{32}^{2}}=\sqrt{38-25-4}=\sqrt{9}=3$$

$$L = \begin{pmatrix}
9 & 0 & 0 \\ 
-5 & 5 & 0 \\ 
5 & 2 & 3
\end{pmatrix}, 
\; \; $$


$$L^{T} = \begin{pmatrix}
9 & -5 & 5 \\ 
0 & 5 & 2 \\ 
0 & 0 & 3
\end{pmatrix}.$$

In [163]:
A = np.array([[9, 0, 0], 
              [-5, 5, 0], 
              [5, 2, 3]])
A.T

array([[ 9, -5,  5],
       [ 0,  5,  2],
       [ 0,  0,  3]])

Решим систему $Ly=b:$

$$\begin{cases}
9y_{1}=531, \\
-5y_{1}+5y_{2}=-460, \\
5y_{1}+2y_{2}+3y_{3}=193.
\end{cases}$$

$\begin{cases}
y_{1} = 59\\
5y_{2}=-460+295=-165\\
295+2y_{2}+3y_{3}=193
\end{cases},
\begin{cases}
y_{1} = 59\\
y_{2}=-33\\
295-66+3y_{3}=193
\end{cases},
\begin{cases}
y_{1} = 59\\
y_{2}=-33\\
3y_{3}=193-295+66=-36
\end{cases},
\begin{cases}
y_{1} = 59\\
y_{2}=-33\\
y_{3}=-12
\end{cases}$


И решим систему $L^{T}x=y:$

$\begin{cases}
9x_{1}-5x_{2}+5x_{3}=59 \\
5x_{2}+2x_{3}=-33 \\
3x_{3}=-12
\end{cases},
\begin{cases}
9x_{1}-5x_{2}+5x_{3}=59 \\
5x_{2}=-33+8=-25 \\
x_{3}=-4.
\end{cases},
\begin{cases}
9x_{1}+25-20=59 \\
5x_{2}=-25 \\
x_{3}=-4
\end{cases},
\begin{cases}
9x_{1}=54 \\
x_{2}=-5 \\
x_{3}=-4
\end{cases},
\begin{cases}
x_{1}=6 \\
x_{2}=-5 \\
x_{3}=-4
\end{cases}$

Проверка, подставляем полученные значения:

$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$

$\begin{cases}
81\cdot 6 -45\cdot(-5)+45\cdot(-4)=531 \\
-45\cdot 6 +50\cdot(-5)-15\cdot(-4)=-460 \\
45\cdot 6 - 15\cdot(-5)+38\cdot(-4)=193
\end{cases},
\begin{cases}
486+225-180=531 \\
-270-250+60=-460 \\
270+75-152=193
\end{cases},
\begin{cases}
531=531 \\
460=-460 \\
193=193
\end{cases}$

Задание__5*.__ Написать на Python программу с реализацией одного из изученных алгоритмов решения СЛАУ.