In [1]:
import numpy as np

Задание__1.__ Найти собственные векторы и собственные значения для линейного оператора, заданного матрицей

$$A=\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}.$$


Решение: 
    
Собственный вектор оператора $\textbf{A}$ — это такой ненулевой вектор, действие оператора на который сводится к умножению его на число:

$$\textbf{A}x=\lambda x.$$

При этом число $\lambda$ называется _собственным значением_ этого оператора.

$$\begin{vmatrix}
-1-\lambda & -6\\ 
2 & 6-\lambda
\end{vmatrix} = 0,$$

$$(-1-\lambda)(6-\lambda)+12=0,$$

$$-6 -6\lambda+\lambda + \lambda^{2}=0,$$

$$6 -5\lambda+\lambda^{2}=0,$$

$$\lambda^{2}-5\lambda+6=0,$$

$$\lambda_{1} = \frac{5+\sqrt{25-4*6}}{2} =\frac{5+\sqrt{1}}{2} = 3$$

$$\lambda_{2} = \frac{5-\sqrt{25-4*6}}{2} =\frac{5-\sqrt{1}}{2}= 2$$


Теперь найдем собственные векторы вида $\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}$, подставив полученное собственное значение в выражение $\textbf{A}x=\lambda x$:

$$\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}=
\lambda
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}
$$

$\lambda_{1} = 3$: 

$\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}=
3
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}
$

$\begin{cases}
-x_{1}-6x_{2}= 3x_{1} \\
2x_{1}+6x_{2}= 3x_{2}
\end{cases}$, 
$\begin{cases}
-4x_{1}= 6x_{2} \\
2x_{1}=-3x_{2}
\end{cases}$, 
$\begin{cases}
-4x_{1}= 6x_{2} \\
2(-\frac{3}{2}x_{2})=-3x_{2}
\end{cases}$, 
$\begin{cases}
x_{1}= -\frac{3}{2}x_{2} \\
x_{2}=x_{2}
\end{cases}$ 

$\lambda_{2} = 2$: 

$\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}=
2
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}
$

$\begin{cases}
-x_{1}-6x_{2}= 2x_{1} \\
2x_{1}+6x_{2}= 2x_{2}
\end{cases}$, 
$\begin{cases}
-6x_{2}= 3x_{1} \\
2x_{1}=-4x_{2}
\end{cases}$, 
$\begin{cases}
-6x_{2}= 3(-2x_{2}) \\
x_{1}=-2x_{2}
\end{cases}$, 
$\begin{cases}
x_{1}=-2x_{2} \\
x_{2}=x_{2}
\end{cases}$ 

In [2]:
A = np.array([[-1, -6], 
              [2, 6]])
w, v = np.linalg.eig(A)
print(f'Матрица A:\n{A}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[-1 -6]
 [ 2  6]]
Собственные значения:
[2. 3.]
Собственные векторы:
[[-0.89442719  0.83205029]
 [ 0.4472136  -0.5547002 ]]


Задание__2.__ Дан оператор поворота на 180 градусов, задаваемый матрицей 

$$A=\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}.$$

Показать, что __любой__ вектор является для него собственным.


Решение:
    
аналогично 

$$\begin{vmatrix}
-1-\lambda & 0\\ 
0 & -1-\lambda
\end{vmatrix} = 0$$

$$(-1-\lambda)(-1-\lambda)=0$$

$$(1+\lambda+\lambda+\lambda^{2})=0$$

$$(1+2\lambda+\lambda^{2})=0$$

$$(\lambda^{2}+2\lambda+1)=0$$

$$\lambda_{1} = \frac{-2+\sqrt{4-4}}{2} = -1$$

$$\lambda_{2} = \frac{-2-\sqrt{4-4}}{2} = -1$$

$\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}=
\lambda
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}
$

$\begin{cases}
-x_{1}+0*x_{2}= -x_{1} \\
0*x_{1}-x_{2}= -x_{2}
\end{cases}$,
$\begin{cases}
-x_{1}= -x_{1} \\
-x_{2}= -x_{2}
\end{cases}$,
$\begin{cases}
x_{1}= x_{1} \\
x_{2}= x_{2}
\end{cases}$

видно что для любых значений $x_{1}$ и $x_{2}$ верно, таким образом любой вектор будет собственным для $A$

In [3]:
A = np.array([[-1, 0], 
              [0, -1]])
w, v = np.linalg.eig(A)
print(f'Матрица A:\n{A}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[-1  0]
 [ 0 -1]]
Собственные значения:
[-1. -1.]
Собственные векторы:
[[1. 0.]
 [0. 1.]]


Задание__3.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}$$

Установить, является ли вектор $x=(1,1)$ собственным вектором этого линейного оператора.

Решение аналогично:

$$\begin{vmatrix}
1-\lambda & 1\\ 
-1 & 3-\lambda
\end{vmatrix} = 0$$

$$(1-\lambda)(3-\lambda)+1=0$$

$$3-3\lambda-\lambda+\lambda^{2}+1=0$$

$$4-4\lambda+\lambda^{2}=0$$

$$\lambda^{2}-4\lambda+4=0$$

$$\lambda_{1} = \frac{4+\sqrt{16-4*4}}{2} =\frac{4}{2}= 2$$

$$\lambda_{2} = \frac{4-\sqrt{16-4*4}}{2} =\frac{4}{2}= 2$$

$$\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}
\begin{pmatrix}
1\\ 
1
\end{pmatrix}=
2
\begin{pmatrix}
1\\ 
1
\end{pmatrix}
$$

$$\begin{cases}
1+1= 2 \\
-1+3= 2
\end{cases},
\begin{cases}
2=2 \\
2=2
\end{cases}$$

так как система верна, 
$x=\begin{pmatrix}
1\\ 
1
\end{pmatrix}$ - является собственным вектором линейного оператора 
$A=\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}$

In [4]:
A = np.array([[1, 1], 
              [-1, 3]])
w, v = np.linalg.eig(A)
print(f'Матрица A:\n{A}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[ 1  1]
 [-1  3]]
Собственные значения:
[2.00000002 1.99999998]
Собственные векторы:
[[ 0.70710677 -0.70710679]
 [ 0.70710679 -0.70710677]]


Задание__4.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix} 0 & 3 & 0\\ 3 & 0 & 0\\ 0 & 0 & 3 \end{pmatrix}$$

Установить, является ли вектор $x=(3, -3, -4)$ собственным вектором этого линейного оператора.

Решение:

$$\begin{pmatrix}
0 & 3 & 0\\ 3 & 0 & 0\\ 0 & 0 & 3
\end{pmatrix}
\begin{pmatrix}
3\\ 
-3\\
-4
\end{pmatrix}=
\lambda
\begin{pmatrix}
3\\ 
-3\\
-4
\end{pmatrix}
$$

$\begin{cases}
0 -9 + 0 = 3\lambda \\
9 + 0 + 0 = -3\lambda \\
0 + 0 + -12 = -4\lambda
\end{cases},
\begin{cases}
-9 = 3\lambda \\
9 = -3\lambda \\
-12 = -4\lambda
\end{cases},
\begin{cases}
-3 = \lambda \\
3 = \lambda
\end{cases},
$ не имеет смысла,

таким образом 
$\begin{pmatrix}
3\\ 
-3\\
-4
\end{pmatrix}$ не является собственным вектором линейного оператора $A=\begin{pmatrix} 0 & 3 & 0\\ 3 & 0 & 0\\ 0 & 0 & 3 \end{pmatrix}$

In [5]:
A = np.array([[0, 3, 0], 
              [3, 0, 0], 
              [0, 0, 3]])
w, v = np.linalg.eig(A)
print(f'Матрица A:\n{A}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[0 3 0]
 [3 0 0]
 [0 0 3]]
Собственные значения:
[ 3. -3.  3.]
Собственные векторы:
[[ 0.70710678 -0.70710678  0.        ]
 [ 0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]
