1. Найдите посредством NumPy SVD для матрицы:

$$\begin{pmatrix}
1 & 2 & 0\\ 
0 & 0 & 5\\ 
3 & -4 & 2\\ 
1 & 6 & 5\\ 
0 & 1 & 0
\end{pmatrix}.$$


2. Для матрицы из предыдущего задания найдите:

    а) евклидову норму;
    
    б) норму Фробениуса.

In [1]:
import numpy as np
np.set_printoptions(precision=2, suppress=True)

In [2]:
A = np.array([[1, 2, 0],
              [0, 0, 5],
              [3, -4, 2],
              [1, 6, 5],
              [0, 1, 0]])
print(f'Матрица A:\n{A}')

Матрица A:
[[ 1  2  0]
 [ 0  0  5]
 [ 3 -4  2]
 [ 1  6  5]
 [ 0  1  0]]


Для любой ненулевой вещественной матрицы $A$ размером $m\times n$ существуют две вещественные ортогональные матрицы $U$ и $V$, такие, что $U^{T}AV$ считается матрицей $D$ размера $m\times n$ с неотрицательными элементами на главной диагонали. В прямоугольной матрице под главной диагональю будем понимать совокупность элементов $d_{ii}$). Все элементы матрицы $D$, не лежащие на главной диагонали, считаются нулевыми.

Представление матрицы $A$ в виде:

$$A=UDV^{T}$$

называется _сингулярным разложением — Singular Values Decomposition, SVD_.

In [17]:

U, s, W = np.linalg.svd(A)

# Транспонируем матрицу W
V = W.T

# s - список диагональных элементов, его нужно привести к виду диагональной матрицы для наглядности
D = np.zeros_like(A, dtype=float) #возвращает массив нулей с той же формой и типом,что и заданный массив.
D[np.diag_indices(min(A.shape))] = s #diag_indices возвращает индексы элементов главной диагонали квадратного 
                                     #массива заданного размера и размерности.

In [4]:
print(f'Матрица D:\n{D}') 

Матрица D:
[[8.82 0.   0.  ]
 [0.   6.14 0.  ]
 [0.   0.   2.53]
 [0.   0.   0.  ]
 [0.   0.   0.  ]]


In [5]:
print(f'сингулярными числами матрицы A:\n{s}')

сингулярными числами матрицы A:
[8.82 6.14 2.53]


In [6]:
print(f'Матрица U:\n{U}')

Матрица U:
[[ 0.17  0.16 -0.53 -0.8  -0.16]
 [ 0.39 -0.53  0.61 -0.43  0.03]
 [-0.14 -0.82 -0.52  0.14  0.07]
 [ 0.89  0.06 -0.25  0.38 -0.06]
 [ 0.08  0.11 -0.08 -0.11  0.98]]


In [7]:
print(np.dot(U.T, U)) # проверка на ортогональность

[[ 1.  0. -0.  0. -0.]
 [ 0.  1.  0.  0.  0.]
 [-0.  0.  1. -0. -0.]
 [ 0.  0. -0.  1. -0.]
 [-0.  0. -0. -0.  1.]]


In [8]:
print(f'Матрица V:\n{V}')

Матрица V:
[[ 0.07 -0.37 -0.93]
 [ 0.72  0.67 -0.21]
 [ 0.69 -0.65  0.31]]


Проверяем результат, подставив полученные значение U, D, V обратно в формулу:
$$A=UDV^{T}$$

In [9]:
print(np.dot(np.dot(U, D), V.T))

[[ 1.  2.  0.]
 [ 0. -0.  5.]
 [ 3. -4.  2.]
 [ 1.  6.  5.]
 [-0.  1. -0.]]


Получили матрицу, соответствующую исходной матрице $A$

Евклидова норма матрицы:
$$\left \| A \right \|_{E}=\text{max}\left (\frac{\left \| Ax \right \|}{\left \| x \right \|}\right )$$

евклидова норма матрицы равна евклидовой норме диагональной матрицы из её сингулярных чисел $D$. Максимальное значение полученного отношения будет равно максимальному сингулярному числу $\mu_{max}$, и, принимая во внимание факт сортировки по убыванию сингулярных чисел, получим:
$$\mu_{1}\geqslant \mu_{2}\geqslant ... \geqslant \mu_{r} > 0.$$
$$\left \| A \right \|_{E}=\mu_{1}.$$



In [10]:
max(s) #ищем максимальное сингулярное число из массива диагональных элементов s

8.824868854820444

In [11]:
s[0] #либо берем первый элемент массива s

8.824868854820444

In [12]:
np.linalg.norm(A, ord=2)  #вариант через функцию linalg.norm() ord = 2

8.824868854820444

Когда известно сингулярное разложение матрицы, её норма Фробениуса вычисляется как:

$$\left \| A \right \|_{F}=\sqrt{\sum_{k=1}^{r}\mu_{k}^{2}}.$$

где $\mu_{k}$ - сингулярные числа матрицы, в данном случае $k=3$
$$\mu_{1}=8.82$$
$$\mu_{2}=6.14$$
$$\mu_{2}=2.53$$

In [13]:
np.sqrt(8.82**2+6.14**2+2.53**2)

11.04051176350082

In [14]:
np.linalg.norm(A, ord = 'fro') #вариант через функцию linalg.norm() fro means Frobenius

11.045361017187261

In [15]:
a_f = 0
for i in s:
    a_f += i**2
np.sqrt(a_f)

11.045361017187263